sudo apt-get install -y \
    pandoc \
    latex-beamer \
    latex-xcolor \
    latexmk \
    biber \
    tex-common \
    tex-gyre \
    texinfo \
    texlive \
    texlive-base \
    texlive-xetex \
    texlive-luatex \
    texlive-binaries \
    texlive-bibtex-extra \
    texlive-extra-utils \
    texlive-font-utils \
    texlive-fonts-recommended \
    texlive-fonts-recommended-doc \
    texlive-generic-recommended \
    texlive-generic-extra \
    texlive-lang-german \
    texlive-latex-base \
    texlive-latex-base-doc \
    texlive-latex-recommended \
    texlive-latex-recommended-doc \
    texlive-pstricks \
    texlive-pstricks-doc \
    texlive-metapost \
    texlive-latex-extra \
    texlive-fonts-extra \
    texlive-science \
    texlive-publishers \
    texlive-humanities \
    mscgen \
    inkscape \
    texstudio \
    latexdiff \

